=== abishek21sa-sketch/aurum-v3/AURUM/schemas/aurum_sbom.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://aurum.local/schemas/aurum_sbom.schema.json",
  "title": "AURUM CycloneDX Software Bill of Materials",
  "type": "object",
  "required": ["bomFormat", "specVersion", "serialNumber", "version", "metadata", "components"],
  "properties": {
    "bomFormat": {"const": "CycloneDX"},
    "specVersion": {"const": "1.5"},
    "serialNumber": {"type": "string", "pattern": "^urn:uuid:"},
    "version": {"const": 1},
    "metadata": {
      "type": "object",
      "required": ["component", "properties"],
      "properties": {
        "component": {"type": "object", "required": ["type", "name"]},
        "properties": {"type": "array", "minItems": 1}
      }
    },
    "components": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["type", "group", "name", "version", "purl"],
        "properties": {
          "type": {"const": "library"},
          "group": {"const": "pypi"},
          "name": {"type": "string", "minLength": 1},
          "version": {"type": "string", "minLength": 1},
          "purl": {"type": "string", "pattern": "^pkg:pypi/"}
        }
      }
    }
  },
  "additionalProperties": true
}

=== abishek21sa-sketch/aurum-v3/AURUM/artifacts/compliance/sbom.json
{
  "bomFormat": "CycloneDX",
  "components": [
    {
      "group": "pypi",
      "name": "altair",
      "purl": "pkg:pypi/altair@6.1.0",
      "type": "library",
      "version": "6.1.0"
    },
    {
      "group": "pypi",
      "name": "annotated-doc",
      "purl": "pkg:pypi/annotated-doc@0.0.4",
      "type": "library",
      "version": "0.0.4"
    },
    {
      "group": "pypi",
      "name": "annotated-types",
      "purl": "pkg:pypi/annotated-types@0.7.0",
      "type": "library",
      "version": "0.7.0"
    },
    {
      "group": "pypi",
      "name": "anyio",
      "purl": "pkg:pypi/anyio@4.13.0",
      "type": "library",
      "version": "4.13.0"
    },
    {
      "group": "pypi",
      "name": "APScheduler",
      "purl": "pkg:pypi/apscheduler@3.11.2",
      "type": "library",
      "version": "3.11.2"
    },
    {
      "group": "pypi",
      "name": "attrs",
      "purl": "pkg:pypi/attrs@26.1.0",
      "type": "library",
      "version": "26.1.0"
    },
    {
      "group": "pypi",
      "name": "beautifulsoup4",
      "purl": "pkg:pypi/beautifulsoup4@4.14.3",
      "type": "library",
      "version": "4.14.3"
    },
    {
      "group": "pypi",
      "name": "blinker",
      "purl": "pkg:pypi/blinker@1.9.0",
      "type": "library",
      "version": "1.9.0"
    },
    {
      "group": "pypi",
      "name": "cachetools",
      "purl": "pkg:pypi/cachetools@7.1.4",
      "type": "library",
      "version": "7.1.4"
    },
    {
      "group": "pypi",
      "name": "certifi",
      "purl": "pkg:pypi/certifi@2026.5.20",
      "type": "library",
      "version": "2026.5.20"
    },
    {
      "group": "pypi",
      "name": "cffi",
      "purl": "pkg:pypi/cffi@2.0.0",
      "type": "library",
      "version": "2.0.0"
    },
    {
      "group": "pypi",
      "name": "charset-normalizer",
      "purl": "pkg:pypi/charset-normalizer@3.4.7",
      "type": "library",
      "version": "3.4.7"
    },
    {
      "group": "pypi",
      "name": "clarabel",
      "purl": "pkg:pypi/clarabel@0.11.1",
      "type": "library",
      "version": "0.11.1"
    },
    {
      "group": "pypi",
      "name": "click",
      "purl": "pkg:pypi/click@8.4.1",
      "type": "library",
      "version": "8.4.1"
    },
    {
      "group": "pypi",
      "name": "colorama",
      "purl": "pkg:pypi/colorama@0.4.6",
      "type": "library",
      "version": "0.4.6"
    },
    {
      "group": "pypi",
      "name": "contourpy",
      "purl": "pkg:pypi/contourpy@1.3.3",
      "type": "library",
      "version": "1.3.3"
    },
    {
      "group": "pypi",
      "name": "curl_cffi",
      "purl": "pkg:pypi/curl-cffi@0.15.0",
      "type": "library",
      "version": "0.15.0"
    },
    {
      "group": "pypi",
      "name": "cvxpy",
      "purl": "pkg:pypi/cvxpy@1.9.0",
      "type": "library",
      "version": "1.9.0"
    },
    {
      "group": "pypi",
      "name": "cycler",
      "purl": "pkg:pypi/cycler@0.12.1",
      "type": "library",
      "version": "0.12.1"
    },
    {
      "group": "pypi",
      "name": "Deprecated",
      "purl": "pkg:pypi/deprecated@1.3.1",
      "type": "library",
      "version": "1.3.1"
    },
    {
      "group": "pypi",
      "name": "distro",
      "purl": "pkg:pypi/distro@1.9.0",
      "type": "library",
      "version": "1.9.0"
    },
    {
      "group": "pypi",
      "name": "fastapi",
      "purl": "pkg:pypi/fastapi@0.136.3",
      "type": "library",
      "version": "0.136.3"
    },
    {
      "group": "pypi",
      "name": "fonttools",
      "purl": "pkg:pypi/fonttools@4.63.0",
      "type": "library",
      "version": "4.63.0"
    },
    {
      "group": "pypi",
      "name": "gevent",
      "purl": "pkg:pypi/gevent@26.5.0",
      "type": "library",
      "version": "26.5.0"
    },
    {
      "group": "pypi",
      "name": "gitdb",
      "purl": "pkg:pypi/gitdb@4.0.12",
      "type": "library",
      "version": "4.0.12"
    },
    {
      "group": "pypi",
      "name": "GitPython",
      "purl": "pkg:pypi/gitpython@3.1.50",
      "type": "library",
      "version": "3.1.50"
    },
    {
      "group": "pypi",
      "name": "greenlet",
      "purl": "pkg:pypi/greenlet@3.5.1",
      "type": "library",
      "version": "3.5.1"
    },
    {
      "group": "pypi",
      "name": "gurobipy",
      "purl": "pkg:pypi/gurobipy@13.0.2",
      "type": "library",
      "version": "13.0.2"
    },
    {
      "group": "pypi",
      "name": "h11",
      "purl": "pkg:pypi/h11@0.16.0",
      "type": "library",
      "version": "0.16.0"
    },
    {
      "group": "pypi",
      "name": "highspy",
      "purl": "pkg:pypi/highspy@1.14.0",
      "type": "library",
      "version": "1.14.0"
    },
    {
      "group": "pypi",
      "name": "hmmlearn",
      "purl": "pkg:pypi/hmmlearn@0.3.3",
      "type": "library",
      "version": "0.3.3"
    },
    {
      "group": "pypi",
      "name": "httpcore",
      "purl": "pkg:pypi/httpcore@1.0.9",
      "type": "library",
      "version": "1.0.9"
    },
    {
      "group": "pypi",
      "name": "httptools",
      "purl": "pkg:pypi/httptools@0.8.0",
      "type": "library",
      "version": "0.8.0"
    },
    {
      "group": "pypi",
      "name": "httpx",
      "purl": "pkg:pypi/httpx@0.28.1",
      "type": "library",
      "version": "0.28.1"
    },
    {
      "group": "pypi",
      "name": "idna",
      "purl": "pkg:pypi/idna@3.16",
      "type": "library",
      "version": "3.16"
    },
    {
      "group": "pypi",
      "name": "iniconfig",
      "purl": "pkg:pypi/iniconfig@2.3.0",
      "type": "library",
      "version": "2.3.0"
    },
    {
      "group": "pypi",
      "name": "itsdangerous",
      "purl": "pkg:pypi/itsdangerous@2.2.0",
      "type": "library",
      "version": "2.2.0"
    },
    {
      "group": "pypi",
      "name": "Jinja2",
      "purl": "pkg:pypi/jinja2@3.1.6",
      "type": "library",
      "version": "3.1.6"
    },
    {
      "group": "pypi",
      "name": "jiter",
      "purl": "pkg:pypi/jiter@0.15.0",
      "type": "library",
      "version": "0.15.0"
    },
    {
      "group": "pypi",
      "name": "joblib",
      "purl": "pkg:pypi/joblib@1.5.3",
      "type": "library",
      "version": "1.5.3"
    },
    {
      "group": "pypi",
      "name": "jsonschema",
      "purl": "pkg:pypi/jsonschema@4.26.0",
      "type": "library",
      "version": "4.26.0"
    },
    {
      "group": "pypi",
      "name": "jsonschema-specifications",
      "purl": "pkg:pypi/jsonschema-specifications@2025.9.1",
      "type": "library",
      "version": "2025.9.1"
    },
    {
      "group": "pypi",
      "name": "kiwisolver",
      "purl": "pkg:pypi/kiwisolver@1.5.0",
      "type": "library",
      "version": "1.5.0"
    },
    {
      "group": "pypi",
      "name": "limits",
      "purl": "pkg:pypi/limits@5.8.0",
      "type": "library",
      "version": "5.8.0"
    },
    {
      "group": "pypi",
      "name": "loguru",
      "purl": "pkg:pypi/loguru@0.7.3",
      "type": "library",
      "version": "0.7.3"
    },
    {
      "group": "pypi",
      "name": "markdown-it-py",
      "purl": "pkg:pypi/markdown-it-py@4.2.0",
      "type": "library",
      "version": "4.2.0"
    },
    {
      "group": "pypi",
      "name": "MarkupSafe",
      "purl": "pkg:pypi/markupsafe@3.0.3",
      "type": "library",
      "version": "3.0.3"
    },
    {
      "group": "pypi",
      "name": "matplotlib",
      "purl": "pkg:pypi/matplotlib@3.10.9",
      "type": "library",
      "version": "3.10.9"
    },
    {
      "group": "pypi",
      "name": "mdurl",
      "purl": "pkg:pypi/mdurl@0.1.2",
      "type": "library",
      "version": "0.1.2"
    },
    {
      "group": "pypi",
      "name": "multitasking",
      "purl": "pkg:pypi/multitasking@0.0.13",
      "type": "library",
      "version": "0.0.13"
    },
    {
      "group": "pypi",
      "name": "narwhals",
      "purl": "pkg:pypi/narwhals@2.21.2",
      "type": "library",
      "version": "2.21.2"
    },
    {
      "group": "pypi",
      "name": "numpy",
      "purl": "pkg:pypi/numpy@2.4.6",
      "type": "library",
      "version": "2.4.6"
    },
    {
      "group": "pypi",
      "name": "openai",
      "purl": "pkg:pypi/openai@2.38.0",
      "type": "library",
      "version": "2.38.0"
    },
    {
      "group": "pypi",
      "name": "osqp",
      "purl": "pkg:pypi/osqp@1.1.1",
      "type": "library",
      "version": "1.1.1"
    },
    {
      "group": "pypi",
      "name": "packaging",
      "purl": "pkg:pypi/packaging@26.2",
      "type": "library",
      "version": "26.2"
    },
    {
      "group": "pypi",
      "name": "pandas",
      "purl": "pkg:pypi/pandas@3.0.3",
      "type": "library",
      "version": "3.0.3"
    },
    {
      "group": "pypi",
      "name": "patsy",
      "purl": "pkg:pypi/patsy@1.0.2",
      "type": "library",
      "version": "1.0.2"
    },
    {
      "group": "pypi",
      "name": "peewee",
      "purl": "pkg:pypi/peewee@4.0.6",
      "type": "library",
      "version": "4.0.6"
    },
    {
      "group": "pypi",
      "name": "pillow",
      "purl": "pkg:pypi/pillow@12.2.0",
      "type": "library",
      "version": "12.2.0"
    },
    {
      "group": "pypi",
      "name": "platformdirs",
      "purl": "pkg:pypi/platformdirs@4.9.6",
      "type": "library",
      "version": "4.9.6"
    },
    {
      "group": "pypi",
      "name": "plotly",
      "purl": "pkg:pypi/plotly@6.7.0",
      "type": "library",
      "version": "6.7.0"
    },
    {
      "group": "pypi",
      "name": "pluggy",
      "purl": "pkg:pypi/pluggy@1.6.0",
      "type": "library",
      "version": "1.6.0"
    },
    {
      "group": "pypi",
      "name": "protobuf",
      "purl": "pkg:pypi/protobuf@7.35.0",
      "type": "library",
      "version": "7.35.0"
    },
    {
      "group": "pypi",
      "name": "psycopg2-binary",
      "purl": "pkg:pypi/psycopg2-binary@2.9.12",
      "type": "library",
      "version": "2.9.12"
    },
    {
      "group": "pypi",
      "name": "pyarrow",
